name: Docker Image Build

on:
  workflow_dispatch

jobs:

  update-filters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: cyrusroshan/generic-docker-run@main
      with:
        command: "docker run --rm -v out:/out siara/adblock2privoxy:2.1.0 -p /out ${{ vars.BLOCKLISTS }}"
