name: Docker Image Build

on:
  push:
  workflow_dispatch:

jobs:

  update-filters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: cyrusroshan/generic-docker-run@main
      with:
        command: "docker pull bsiara/adblock2privoxy:2.1.0"
    - name: build image
      run: |
        TIMESTAMP=$(date +%s)
        docker run -v config:/out bsiara/adblock2privoxy:2.1.0 -p /out ${{ vars.BLOCKLISTS }}
        docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${TIMESTAMP} .
        docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${TIMESTAMP}
