name: Docker Image Build

on:
  workflow_dispatch

jobs:

  update-filters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cyrusroshan/generic-docker-run@main
      with:
        command: "docker run -it --rm -v out:/out siara/adblock2privoxy:2.1.0 -p /out ${{ vars.BLOCKLISTS }}"
